### ISSUE TITLE
pivnet-cli relies on TMPDIR environment variable?

### ISSUE THREAD

**Issue by menicosia** [pivotal-cf/pivnet-cli#10]
This isn't serious, but I noticed that when calling `pivnet` from a script:
- if I set TMPDIR to `/var/tmp/t/` (a directory which doesn't exist), the `pivnet` CLI freaks out

```
+ TMPDIR=/var/tmp/t
+ pivnet login --api-token=[redacted]
Get https://network.pivotal.io/api/v2/authentication: x509: failed to load system roots and no roots provided; mkdir /var/tmp/t/x509trustpolicy251829511: no such file or directory
```

I can fix this either by not using the TMPDIR variable, or creating the directory before calling `pivnet login`, so this isn't an urgent issue for me, more of an FYI for you.

**Comment by pnikonowicz** [comment]
thanks for letting us know :)
I suppose the only work around I can think of is to create the the tempDir automatically, but that might have the unintended consequence of using a folder that the user did not intend to be used. I will close this issue for now, but if you disagree or can think of another pressing scenario that may increase the severity of this issue, please let us know.
