### ISSUE TITLE
Ubuntu/Debian package available

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/pivnet-cli#11]
For anyone who wants to install `pivnet` to Ubuntu/Debian via `apt-get install` I've added an `pivnet-cli` package to [our APT repo](https://apt.starkandwayne.com), and new versions will be automatically rebuilt with each new github release.

```
wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | apt-key add -
echo "deb http://apt.starkandwayne.com stable main" | tee /etc/apt/sources.list.d/starkandwayne.list
apt-get update

apt-get install pivnet-cli
```

Thanks for `pivnet`!

**Comment by zachgersh** [comment]
thanks @drnic - would you mind PR'ing this to the readme (just like I think you may have done for `om`). I can make the change as well if you can't get around to it.
