### ISSUE TITLE
Subcommands parsing global flags rather than erroring

### ISSUE THREAD

**Issue by kirederik** [pivotal-cf/pivnet-cli#12]
When you run a subcommand with a wrong flag, the CLI gives you a nice error:

```bash
$> pivnet products -o                                                                                          
unknown flag `o'
```

But if the flag is a valid global flag, the CLI doesn't error:

```bash
$> pivnet products -v  # this command is equivalent to pivnet -v
0.0.49
```

Would be nice to have a similar error message rather than parsing the global flag.

**Comment by kartiklunkad26** [comment]
@kirederik Thanks for bringing up this issue! I've added this to our tracker backlog!

**Comment by pnikonowicz** [comment]
This looks to be a bug in our dependent library https://github.com/jessevdk/go-flags.

Would you like us to file this on their issue page or would you like to so that you can continue to track this?

Closing this for now.
