### ISSUE TITLE
running dlpf  against ops-manager  seems to be trying to download bosh stemcells?

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pivnet-cli#13]
Running pivnet dlpf seems to be trying to download bosh stemcells not the ops-manager ovf. 

pivnet dlpf -p ops-manager -r 1.12.1 -g *vsphere*
No product files found for ids: [] or globs: [bosh-stemcell-3312.28-vsphere-esxi-ubuntu-trusty-go_agent.tgz]

pivnet dlpf -p ops-manager -r 1.12.3 -g *vsphere*
No product files found for ids: [] or globs: [bosh-stemcell-3312.28-vsphere-esxi-ubuntu-trusty-go_agent.tgz]

**Comment by kartiklunkad26** [comment]
Hey @bhudlemeyer Did you try running this command instead `pivnet dlpf -p ops-manager -r 1.12.1 -g *vsphere*` I just tried this and was able to successfully download using the above command! Hence wanted to ask!

Happy re-open the issue if you're seeing it!
