### ISSUE TITLE
Homebrew: Failed to download resource "pivnet-cli"

### ISSUE THREAD

**Issue by dlresende** [pivotal-cf/pivnet-cli#20]
We have been trying to upgrade `pivnet-cli` via Homebrew without success :(

```
$ brew upgrade pivnet-cli
==> Upgrading 1 outdated package, with result:
pivotal/tap/pivnet-cli 0.0.49 -> 0.0.50
==> Upgrading pivotal/tap/pivnet-cli
==> Downloading https://github.com/pivotal-cf/pivnet-cli/releases/download/v0.0.50/pivnet-darwin-amd64-0.0.50

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pivnet-cli"
Download failed: https://github.com/pivotal-cf/pivnet-cli/releases/download/v0.0.50/pivnet-darwin-amd64-0.0.50
```

Our guess is that version [0.0.50](https://github.com/pivotal-cf/pivnet-cli/releases/tag/v0.0.50) does not have binary files  available for download (which are still available in version [0.0.49](https://github.com/pivotal-cf/pivnet-cli/releases/tag/v0.0.49)).

**Comment by pivotal-gabriel-dumitrescu** [comment]
We've uploaded the binaries for the v0.0.50 and are now available for download.
