### ISSUE TITLE
file-group command cannot specify release - so files are not found

### ISSUE THREAD

**Issue by matthewfischer** [pivotal-cf/pivnet-cli#21]
Given a set of file groups, for example, for PKS:

```ubuntu@bosh-stemcell:~$ pivnet file-groups -p pivotal-container-service -r 1.0.4
+-----+-----------------------+--------------------------------+
| ID  |         NAME          |       PRODUCT FILE NAMES       |
+-----+-----------------------+--------------------------------+
| 977 | PKS CLI - v1.0.4      | PKS CLI - Mac, PKS CLI -       |
|     |                       | Linux, PKS CLI - Windows       |
| 978 | Kubectl CLIs - v1.9.7 | Kubectl v1.9.7 - Mac, Kubectl  |
|     |                       | v1.9.7 - Linux, Kubectl v1.9.7 |
|     |                       | - Windows                      |
+-----+-----------------------+--------------------------------+
```

We try to pull information for a specific one, say, 977 and get an error:

```
 ubuntu@bosh-stemcell:~$ pivnet file-group -p pivotal-container-service -i 977
 Pivnet returned 403 - cannot view file groups for product 'pivotal-container-service'.
```
It appears to me that the fg command, like the pf command, needs a -r flag so that the release version can be specified in the http request.

**Comment by vitakras** [comment]
This issue will be addressed at the same time as https://github.com/pivotal-cf/pivnet-cli/issues/22

**Comment by pivotal-ivan-wang** [comment]
As of v0.0.51, ids will now show under product file column. This should cover the use case for viewing product files of file groups of a specific release.

The original reason why it is not symmetrical with the product file command, is that specifying the file group id of a specific release is not supported by the api. (https://network.pivotal.io/docs/api#release_file_groups)
