### ISSUE TITLE
Support of the new UAA API Token Flow

### ISSUE THREAD

**Issue by ywei2017** [pivotal-cf/pivnet-cli#24]
Any thought on timing to support the new [UAA API Token Flow](https://network.pivotal.io/docs/api). Not sure when pivnet will stop supporting the legacy token, it is possibly a good idea to support the new token flow anyway, for better security.

**Comment by xtreme-debbie-chen** [comment]
@ywei2017 The newest version of pivnet-cli (v0.0.51) should support the UAA API token flow. For the `login` command, use your refresh token for `--api-token` instead of the legacy token. We will update the documentation to be clearer about that.

**Comment by ywei2017** [comment]
@xtreme-debbie-chen Thank you, speedy response :+1:  I will try it out.
