### ISSUE TITLE
Pivnet returned 403 - not allowed to index

### ISSUE THREAD

**Issue by rlewkowicz** [pivotal-cf/pivnet-cli#31]
`pivnet rs -p pivotal-cf` worked once and now throws `Pivnet returned 403 - not allowed to index`. Other products work fine.

**Comment by pivotal-ivan-wang** [comment]
Hi @rlewkowicz. This appears like your permissions may have changed. If you are a commercial customer of Pivotal please reach out to your customer support representative.

**Comment by rlewkowicz** [comment]
@pivotal-ivan-wang 
I'll reach out to them, but as a heads up I can goto the download page in the pivotal network and grab it, just not through pivnet. I *think* I saw cf 2.4.x when I did the pivnet and I almost wonder if it didn't like that. I don't think thats GA yet. I was able to list the versions one time and it started messing up after that.
