### ISSUE TITLE
Bump Version please

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/pivnet-cli#35]
I get this message now:

`Warning: Your version of Pivnet CLI (0.0.59) does not match the currently released version (0.0.58).`

**Comment by rszumlakowski** [comment]
Thank you for raising this issue.  It's likely because we released a new version of Pivnet CLI but haven't deployed a new instance of the server yet.  I'll look into it.

**Comment by xtreme-behrouz-soroushian** [comment]
As of `Pivnet CLI 0.0.70` this issue should be fixed.
