### ISSUE TITLE
Update product slug name for Spring Cloud Service 3.x

### ISSUE THREAD

**Issue by runningfoo** [pivotal-cf/pivnet-cli#36]
Are there plans to update the cli to sync up with the new product slug and file name for SCS 3.x to be p_spring-cloud-services?

  * The product slug name for SCS 3.x on Pivnet is still p-spring-cloud-services
  * The file name for the SCS 3.x is p_spring-cloud-services
  * The product slug name for SCS 3.x when deployed to PCF is p_spring-cloud-services

We are using the cli for automation to upgrade PCF tiles- and had to account for these variances. Ideally we just have a new product slug for SCS 3.x.

Thanks!

**Comment by rszumlakowski** [comment]
There are no products at this time on Pivnet that have slugs that start with `p_` and there are many that start with `p-`.  We have no plans, at this time, to change the slug for SCS to `p_spring-cloud-services` unless the Spring Cloud Services team approached us and requested the change.

**Comment by rszumlakowski** [comment]
I'm going to look into making an alias slug `p_spring-cloud-services` for `p-spring-cloud-services`.  I'll let you know after we make the change.

**Comment by nedenwalker** [comment]
@runningfoo Please note that an alias slug `p_spring-cloud-services` was created for `p-spring-cloud-services`. Please try out the cli and verify that this now works as you intend. Thank you.

**Comment by nedenwalker** [comment]
Closing this issue, but please reopen if the need arises.

**Comment by runningfoo** [comment]
This is working as expected. Thank you!
