### ISSUE TITLE
yaml: unmarshal error on running

### ISSUE THREAD

**Issue by nickypike** [pivotal-cf/pivnet-cli#41]
Attempting to run any subcommand of pivnet results in the following error.

pivnet login --api-token=<redacted>
yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `PIVNET_...` into rc.PivnetRC

I've attempted to uninstall/reinstall via brew, download the binary for MacOS, but get this error every time.

**Comment by nickypike** [comment]
Figured out the issue with the help of a friend.  Corrupt pivnetrc file.  Deleted and it worked

**Comment by nedenwalker** [comment]
Cool beans
