### ISSUE TITLE
Description for installing the binary on Ubuntu

### ISSUE THREAD

**Issue by kartiklunkad26** [pivotal-cf/pivnet-cli#5]
The pivnet cli could be very useful to use on the OpsManager VM. Hence the installation instructions to do that on an Ubuntu VM would be very useful! Thank you!

**Comment by robdimsdale** [comment]
@kartiklunkad26 

I can see how it would be useful from the ops manager VM. We can update the README with instructions, but they're not very complex - download the latest binary, make it executable, and put it in the path. There's nothing special to do here.

**Comment by kartiklunkad26** [comment]
That's what I did :-) agreed nothing complex there.

**Comment by robdimsdale** [comment]
I've added some basic instructions to the README - they will be on the `master` branch with the next release.
