### ISSUE TITLE
Asset for Windows wasn't released

### ISSUE THREAD

**Issue by suzuki-shunsuke** [pivotal-cf/pivnet-cli#50]
v4.1.1 doesn't have an asset for Windows.

https://github.com/pivotal-cf/pivnet-cli/releases/tag/v4.1.1

<img width="345" alt="image" src="https://github.com/pivotal-cf/pivnet-cli/assets/13323303/cf38b6c7-53b0-438f-94e3-903e48a92027">

Could you release an asset for Windows?

**Comment by pivotalfish** [comment]
Hi Shunsuke,
Current runway pipeline had limitation for windows infra. We are working to add support for Windows.
Thank you,
Sumit

From: Shunsuke Suzuki ***@***.***>
Date: Wednesday, 27 September 2023 at 3:25 AM
To: pivotal-cf/pivnet-cli ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pivotal-cf/pivnet-cli] Asset for Windows wasn't released (Issue #50)

v4.1.1 doesn't have an asset for Windows.

https://github.com/pivotal-cf/pivnet-cli/releases/tag/v4.1.1
[Image removed by sender. image]<https://user-images.githubusercontent.com/13323303/270805818-cf38b6c7-53b0-438f-94e3-903e48a92027.png>

Could you release an asset for Windows?

**Comment by pivotalfish** [comment]
Windows support is added now.

From: Sumit Jha ***@***.***>
Date: Wednesday, 27 September 2023 at 12:31 PM
To: pivotal-cf/pivnet-cli ***@***.***>, pivotal-cf/pivnet-cli ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [pivotal-cf/pivnet-cli] Asset for Windows wasn't released (Issue #50)
Hi Shunsuke,
Current runway pipeline had limitation for windows infra. We are working to add support for Windows.
Thank you,
Sumit

From: Shunsuke Suzuki ***@***.***>
Date: Wednesday, 27 September 2023 at 3:25 AM
To: pivotal-cf/pivnet-cli ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pivotal-cf/pivnet-cli] Asset for Windows wasn't released (Issue #50)

v4.1.1 doesn't have an asset for Windows.

https://github.com/pivotal-cf/pivnet-cli/releases/tag/v4.1.1
[Image removed by sender. image]<https://user-images.githubusercontent.com/13323303/270805818-cf38b6c7-53b0-438f-94e3-903e48a92027.png>

Could you release an asset for Windows?

**Comment by suzuki-shunsuke** [comment]
Thank you for fixing quickly.
I confirmed an asset for Windows were added to v4.1.1.

https://github.com/pivotal-cf/pivnet-cli/releases/tag/v4.1.1

<img width="298" alt="image" src="https://github.com/pivotal-cf/pivnet-cli/assets/13323303/0a078fd5-26ae-45b0-8c73-a39bc6715d9e">
