### ISSUE TITLE
EULA Error when attempting to download product files

### ISSUE THREAD

**Issue by j-kaplan** [pivotal-cf/pivnet-cli#8]
Recently we started getting an error trying to download a new product file for the first time stating: "The EULA has not been accepted". Command:
`pivnet download-product-files --accept-eula -p $PRODUCT_SLUG -r $RELEASE_VERSION -i $product_file_id -d product-files/`

Output: 
```
Logged-in successfully
Downloading product file: "product-files/elastic-runtime/cf-1.10.8-build.7.pivotal"
The EULA has not been accepted.
```

Cli version: 0.0.49

The command works after manually logging into pivnet with a browser and starting a download of the product file in question.

**Comment by kartiklunkad26** [comment]
Hi! 
Apologies for a super late response, but I'll be closing this story. If you are still seeing this as an issue, please re-open them! We are looking to be more responsive going forward :)
